# Generated by Django 4.2.29 on 2026-04-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first. Use this to reorder products.'),
        ),
    ]
